

#define this module
MODULE	= utility

#define the modules it depends on
#important: the order should reflect the desired order for linking
DEPENDMODS = 

# IN GENERAL,  DO NOT CHANGE ANY LINES BELOW THIS POINT
# IMPORTANT: MakeDefns must be included before MakeRules!

#include common definitions
include ../../MakeDefns

# specify what it means by "make all" and "make clean"

all: $(OBJLIB)

clean: cleanlib

#include common rules
include ../../MakeRules


