

#define this module
MODULE	= utility

#define the modules it depends on
#important: the order should reflect the desired order for linking
DEPENDMODS = 

# IN GENERAL,  DO NOT CHANGE ANY LINES BELOW THIS POINT

include ../../MakeMod
