

#define this module
MODULE	= retrieval

#define the modules it depends on
#important: the order should reflect the desired order for linking
DEPENDMODS = index utility

# IN GENERAL,  DO NOT CHANGE ANY LINES BELOW THIS POINT

include ../../MakeMod
