#line 2 "../src/WebParser.cpp"

#line 4 "../src/WebParser.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 33
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE webrestart(webin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int webleng;

extern FILE *webin, *webout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up webtext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up webtext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef unsigned int yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via webrestart()), so that the user can continue scanning by
	 * just pointing webin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when webtext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int webleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow webwrap()'s to do buffer switches
 * instead of setting up a fresh webin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void webrestart (FILE *input_file  );
void web_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE web_create_buffer (FILE *file,int size  );
void web_delete_buffer (YY_BUFFER_STATE b  );
void web_flush_buffer (YY_BUFFER_STATE b  );
void webpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void webpop_buffer_state (void );

static void webensure_buffer_stack (void );
static void web_load_buffer_state (void );
static void web_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER web_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE web_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE web_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE web_scan_bytes (yyconst char *bytes,int len  );

void *weballoc (yy_size_t  );
void *webrealloc (void *,yy_size_t  );
void webfree (void *  );

#define yy_new_buffer web_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        webensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            web_create_buffer(webin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        webensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            web_create_buffer(webin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define webwrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *webin = (FILE *) 0, *webout = (FILE *) 0;

typedef int yy_state_type;

extern int weblineno;

int weblineno = 1;

extern char *webtext;
#define yytext_ptr webtext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up webtext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	webleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 30
#define YY_END_OF_BUFFER 31
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[133] =
    {   0,
        0,    0,   31,   29,   28,   29,   29,   29,   23,   29,
       23,    0,    0,    0,    0,    0,   23,    0,    0,    0,
        0,    0,    0,    0,    0,   22,    0,   21,   20,    0,
       17,   26,    0,    0,    0,    0,    0,    0,    0,   18,
        0,    0,    0,    0,    0,    0,    0,   23,   24,    0,
       19,   16,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   27,   25,    0,    0,    0,    0,    0,    0,
        1,    0,    0,    0,    0,    0,    0,    0,    2,    0,
        0,    0,    0,    0,    0,   14,    0,    0,    0,    0,
        0,    0,   15,    0,    0,    0,    0,    0,    0,   18,

        0,    0,    0,    8,    0,   12,    0,    0,    0,    9,
       13,    3,    0,    0,    0,    0,   10,    4,    0,   11,
        0,    0,    0,    0,    6,    7,    0,    0,    0,    0,
        5,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    1,    4,    1,    1,    5,    6,    1,
        1,    7,    1,    1,    8,    9,   10,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,    1,   12,   13,
        1,   14,    1,    1,   15,   16,   17,   18,   19,   16,
       16,   20,   21,   16,   16,   22,   16,   23,   24,   25,
       16,   26,   27,   28,   16,   16,   16,   16,   29,   16,
        1,    1,    1,    1,    1,    1,   30,   31,   32,   33,

       34,   31,   31,   31,   35,   31,   31,   36,   31,   31,
       37,   38,   31,   39,   40,   41,   31,   31,   31,   31,
       42,   31,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[43] =
    {   0,
        1,    1,    2,    3,    1,    4,    1,    1,    1,    2,
        4,    1,    1,    1,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6
    } ;

static yyconst flex_int16_t yy_base[146] =
    {   0,
        0,    0,  341,  342,  342,  336,  305,  330,  331,   40,
       76,   33,   42,  299,  321,    0,  328,  325,  116,  318,
       33,   38,   39,   47,    0,   50,   53,  342,  342,  291,
      342,    0,  316,  321,  106,  110,  111,  125,  314,  342,
      109,   55,  115,  119,  117,  318,  286,  319,  342,  310,
      342,  342,  138,   61,  121,  139,  145,  148,  151,  149,
      155,  158,    0,    0,  164,  173,  171,  174,  181,  309,
      342,   70,   62,  185,  175,  190,  197,  308,  342,  187,
      198,  194,  204,  207,  307,  342,   57,  306,  211,  208,
      305,  304,  342,  150,  216,  214,  251,  250,  243,  241,

      221,  239,  238,  342,  237,  342,  234,  223,  233,  342,
      342,  342,  232,  229,  219,  213,  342,  342,  226,  342,
      197,  200,  188,  166,  342,  342,  111,   99,   65,   37,
      342,  342,  253,  256,  261,  263,  269,  275,   44,  281,
      287,  293,  299,  305,  311
    } ;

static yyconst flex_int16_t yy_def[146] =
    {   0,
      132,    1,  132,  132,  132,  133,  132,  132,  134,  135,
      132,  132,  133,  132,  132,  136,  134,  137,  135,  138,
      138,  138,  138,  138,  139,   11,  132,  132,  132,  132,
      132,  136,  140,  132,  138,  138,  138,  138,  138,  132,
      138,  138,  138,  138,  138,  132,  136,  134,  132,  140,
      132,  132,  138,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  139,  136,  138,  138,  138,  138,  138,  141,
      132,  138,  138,  138,  138,  138,  138,  138,  132,  138,
      138,  138,  138,  138,  141,  132,  138,  138,  138,  138,
      142,  143,  132,  138,  138,  138,  138,  138,  138,  144,

      138,  145,  142,  132,  143,  132,  138,  138,  138,  132,
      132,  132,  144,  132,  138,  145,  132,  132,  138,  132,
      132,  138,  138,  132,  132,  132,  132,  132,  132,  132,
      132,    0,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132
    } ;

static yyconst flex_int16_t yy_nxt[385] =
    {   0,
        4,    5,    4,    4,    6,    4,    7,    8,    4,    4,
        9,    4,   10,    4,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,   18,   27,   28,  132,   40,   41,   46,   19,
      131,   40,   40,   29,   43,   47,   42,   21,  132,   45,
       40,   41,   41,   27,   28,   44,   22,   23,   40,   43,
       40,   59,   24,   45,   40,   40,   41,   66,   44,   22,
       23,   16,   99,   40,   25,   88,   17,   87,  130,   48,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,

       26,   26,   26,   26,   26,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,  132,   40,
       53,  129,   40,   40,   40,  132,   55,  128,   40,   54,
       40,   57,   40,   35,   40,   53,   58,   56,   40,   53,
       60,   55,   36,   37,   62,   57,   67,   61,   38,   58,
       56,   40,   40,   60,   53,   36,   37,   62,   40,   67,
       61,   40,   40,   40,   71,   65,   70,   68,   40,   75,
       72,   40,   69,   73,   74,  107,   76,   40,   65,   77,
       68,   70,   78,   75,   40,   69,   79,   40,   40,  127,
       76,   82,   80,   77,   40,   83,   81,   78,   40,   90,

       40,  126,   84,   40,   94,   82,   89,   40,   91,   83,
       40,   40,   90,  125,  124,   92,   84,   40,   96,   95,
       40,   40,   97,   91,   40,   98,  117,   40,  101,   40,
       92,   96,   40,  108,   40,  102,   40,   97,  121,   40,
       98,  109,  122,  115,  114,  119,  120,  118,  102,  123,
      106,  104,  117,  114,  109,   13,  112,   13,   13,   17,
       17,   17,   20,  111,  110,   20,   20,   32,   32,   33,
       33,   33,   33,   33,   33,   39,   39,   39,   39,   39,
       39,   50,   50,   50,   50,   50,   50,   85,   85,   85,
       85,   85,   85,  103,  103,  103,  103,  103,  103,  105,

      105,  105,  105,  105,  105,  113,  113,  113,  113,  113,
      113,  116,  116,  116,  116,  116,  116,  106,  104,  100,
       86,   93,   86,   51,   16,   64,   63,   40,   52,   51,
       49,   40,   34,   16,   31,   30,   16,   15,   14,   12,
      132,    3,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132
    } ;

static yyconst flex_int16_t yy_chk[385] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,   10,   12,   12,   13,   21,   21,  139,   10,
      130,   22,   23,   13,   22,   26,   21,   10,   26,   23,
       24,   24,   21,   27,   27,   22,   10,   10,   42,   22,
       87,   42,   10,   23,   54,   73,   24,   54,   22,   10,
       10,   11,   87,   72,   11,   73,   11,   72,  129,   26,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,

       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   19,   35,
       35,  128,   41,   36,   37,   19,   36,  127,   43,   35,
       45,   37,   44,   19,   55,   35,   41,   36,   38,   38,
       43,   36,   19,   19,   45,   37,   55,   44,   19,   41,
       36,   53,   56,   43,   38,   19,   19,   45,   57,   55,
       44,   58,   60,   94,   59,   53,   58,   56,   61,   60,
       59,   62,   57,   59,   59,   94,   61,   65,   53,   62,
       56,   58,   65,   60,   67,   57,   66,   68,   75,  124,
       61,   67,   66,   62,   69,   68,   66,   65,   74,   75,

       80,  123,   69,   76,   80,   67,   74,   82,   76,   68,
       77,   81,   75,  122,  121,   77,   69,   83,   82,   81,
       84,   90,   83,   76,   89,   84,  116,   96,   89,   95,
       77,   82,  115,   95,  101,   90,  108,   83,  114,  119,
       84,   96,  115,  101,  113,  108,  109,  107,   90,  119,
      105,  103,  102,  100,   96,  133,   99,  133,  133,  134,
      134,  134,  135,   98,   97,  135,  135,  136,  136,  137,
      137,  137,  137,  137,  137,  138,  138,  138,  138,  138,
      138,  140,  140,  140,  140,  140,  140,  141,  141,  141,
      141,  141,  141,  142,  142,  142,  142,  142,  142,  143,

      143,  143,  143,  143,  143,  144,  144,  144,  144,  144,
      144,  145,  145,  145,  145,  145,  145,   92,   91,   88,
       85,   78,   70,   50,   48,   47,   46,   39,   34,   33,
       30,   20,   18,   17,   15,   14,    9,    8,    7,    6,
        3,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  132
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int web_flex_debug;
int web_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *webtext;
#line 1 "../src/WebParser.l"
#line 5 "../src/WebParser.l"

/*==========================================================================
 * Copyright (c) 2001 Carnegie Mellon University.  All Rights Reserved.
 *
 * Use of the Lemur Toolkit for Language Modeling and Information Retrieval
 * is subject to the terms of the software license set forth in the LICENSE
 * file included with this software, and also available at
 * http://www.lemurproject.org/license.html
 *
 *==========================================================================
*/

#include "WebParser.hpp"

#include <cstring>

#include <cctype>
#include <cstdlib>
#include <cstdio>


#include <iostream>
#include <fstream>

#define B_DOC 1
#define E_DOC 2
#define B_DOCHDR 12
#define E_DOCHDR 13
#define F_DOCNO 3
#define B_DOCOLDNO 4
#define E_DOCOLDNO 5
#define B_SCRIPT 6
#define E_SCRIPT 7
#define B_COMMENT 8
#define E_COMMENT 9
#define WORD 11
#define UPWORD 18
#define CONTRACTION 14
#define ACRONYM 15
#define ACRONYM2 17
#define UNKNOWN 16
#define B_STYLE 19
#define E_STYLE 20
#define B_TITLE 21
#define E_TITLE 22
#define B_DATE 25
#define E_DATE 26


extern FILE * webin;
extern char * webtext;

long webloc;


#line 643 "../src/WebParser.cpp"

#define INITIAL 0

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int webwrap (void );
#else
extern int webwrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( webtext, webleng, 1, webout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( webin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( webin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, webin))==0 && ferror(webin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(webin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int weblex (void);

#define YY_DECL int weblex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after webtext and webleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 61 "../src/WebParser.l"


#line 799 "../src/WebParser.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! webin )
			webin = stdin;

		if ( ! webout )
			webout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			webensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				web_create_buffer(webin,YY_BUF_SIZE );
		}

		web_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of webtext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 133 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 132 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 63 "../src/WebParser.l"
{webloc += webleng; return B_DOC; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 64 "../src/WebParser.l"
{webloc += webleng; return E_DOC; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 65 "../src/WebParser.l"
{webloc += webleng; return B_DOCHDR; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 66 "../src/WebParser.l"
{webloc += webleng; return E_DOCHDR; }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 67 "../src/WebParser.l"
{webloc += webleng; return F_DOCNO; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 68 "../src/WebParser.l"
{webloc += webleng; return B_DOCOLDNO; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 69 "../src/WebParser.l"
{webloc += webleng; return E_DOCOLDNO; }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 70 "../src/WebParser.l"
{webloc += webleng; return B_STYLE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 71 "../src/WebParser.l"
{webloc += webleng; return E_STYLE; } 
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 72 "../src/WebParser.l"
{webloc += webleng; return B_SCRIPT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 73 "../src/WebParser.l"
{webloc += webleng; return E_SCRIPT; } 
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 74 "../src/WebParser.l"
{webloc += webleng; return B_TITLE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 75 "../src/WebParser.l"
{webloc += webleng; return E_TITLE; }
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 76 "../src/WebParser.l"
{webloc += webleng; return B_DATE; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 77 "../src/WebParser.l"
{webloc += webleng; return E_DATE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 78 "../src/WebParser.l"
{webloc += webleng; return B_COMMENT; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 79 "../src/WebParser.l"
{webloc += webleng; return E_COMMENT; }
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 80 "../src/WebParser.l"
{webloc += webleng; /* zap tags */ }
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 81 "../src/WebParser.l"
{webloc += webleng; /* zap other tags*/}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 82 "../src/WebParser.l"
{webloc += webleng; /* zap symbols */ }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 83 "../src/WebParser.l"
{webloc += webleng; /* zap symbols */ } 
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 84 "../src/WebParser.l"
{webloc += webleng; return UPWORD; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 85 "../src/WebParser.l"
{webloc += webleng; return WORD; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 86 "../src/WebParser.l"
{ webloc += webleng; return WORD; /* *eos token for summarization module */}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 87 "../src/WebParser.l"
{webloc += webleng; return ACRONYM2; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 88 "../src/WebParser.l"
{webloc += webleng; return CONTRACTION;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 89 "../src/WebParser.l"
{webloc += webleng; return ACRONYM; }
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 90 "../src/WebParser.l"
{webloc += webleng; /* zap newline */ }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 91 "../src/WebParser.l"
{webloc += webleng; return UNKNOWN; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 93 "../src/WebParser.l"
ECHO;
	YY_BREAK
#line 1036 "../src/WebParser.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed webin at a new source and called
			 * weblex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = webin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( webwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * webtext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of weblex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					webrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			webrestart(webin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 133 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 133 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 132);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up webtext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					webrestart(webin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( webwrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve webtext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void webrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        webensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            web_create_buffer(webin,YY_BUF_SIZE );
	}

	web_init_buffer(YY_CURRENT_BUFFER,input_file );
	web_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void web_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		webpop_buffer_state();
	 *		webpush_buffer_state(new_buffer);
     */
	webensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	web_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (webwrap()) processing, but the only time this flag
	 * is looked at is after webwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void web_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	webin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE web_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) weballoc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in web_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) weballoc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in web_create_buffer()" );

	b->yy_is_our_buffer = 1;

	web_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with web_create_buffer()
 * 
 */
    void web_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		webfree((void *) b->yy_ch_buf  );

	webfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a webrestart() or at EOF.
 */
    static void web_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	web_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then web_init_buffer was _probably_
     * called from webrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void web_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		web_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void webpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	webensure_buffer_stack();

	/* This block is copied from web_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from web_switch_to_buffer. */
	web_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void webpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	web_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		web_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void webensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)weballoc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)webrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE web_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) weballoc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in web_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	web_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to weblex() will
 * scan from a @e copy of @a str.
 * @param str a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       web_scan_bytes() instead.
 */
YY_BUFFER_STATE web_scan_string (yyconst char * yystr )
{
    
	return web_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to weblex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE web_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) weballoc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in web_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = web_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in web_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up webtext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		webtext[webleng] = (yy_hold_char); \
		(yy_c_buf_p) = webtext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		webleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int webget_lineno  (void)
{
        
    return weblineno;
}

/** Get the input stream.
 * 
 */
FILE *webget_in  (void)
{
        return webin;
}

/** Get the output stream.
 * 
 */
FILE *webget_out  (void)
{
        return webout;
}

/** Get the length of the current token.
 * 
 */
int webget_leng  (void)
{
        return webleng;
}

/** Get the current token.
 * 
 */

char *webget_text  (void)
{
        return webtext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void webset_lineno (int  line_number )
{
    
    weblineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see web_switch_to_buffer
 */
void webset_in (FILE *  in_str )
{
        webin = in_str ;
}

void webset_out (FILE *  out_str )
{
        webout = out_str ;
}

int webget_debug  (void)
{
        return web_flex_debug;
}

void webset_debug (int  bdebug )
{
        web_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from weblex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    webin = stdin;
    webout = stdout;
#else
    webin = (FILE *) 0;
    webout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * weblex_init()
     */
    return 0;
}

/* weblex_destroy is for both reentrant and non-reentrant scanners. */
int weblex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		web_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		webpop_buffer_state();
	}

	/* Destroy the stack itself. */
	webfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * weblex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *weballoc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *webrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void webfree (void * ptr )
{
	free( (char *) ptr );	/* see webrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 93 "../src/WebParser.l"



#define OUTER 0
#define DOC 1
#define DOCOLDNO 7
#define DOCHDR 3
#define SCRIPT 4
#define COMMENT 5
#define TAG 6
#define SYMBOL 8
#define STYLE 9

lemur::parse::WebParser::WebParser() {
  state = OUTER;
// tags for signaling the beginning and ending of an element
// for ElemDocMgr, actual tag values don't matter as long as 
// begin and end tags send same value. Retrieve later using same string
  begelem.setName("B_ELEM");
  endelem.setName("E_ELEM");
  begelem.setValue("\0");
  endelem.setValue("\0");
  iden=identifier;
}

long lemur::parse::WebParser::fileTell() const {
  return webloc;
}

void 
lemur::parse::WebParser::parseFile(const string &filename) {
  parsefile = filename;
  webloc = 0;
  webin = fopen(filename.c_str(), "rb");
  doParse();
  fclose(webin);
}

void lemur::parse::WebParser::parseBuffer (char* buf, int len) {
  int tpos = webloc;
  webloc = 0;
  YY_BUFFER_STATE oldBuf = YY_CURRENT_BUFFER;
  YY_BUFFER_STATE myBuf = web_scan_bytes(buf,len);
  doParse();
  if (oldBuf) web_switch_to_buffer(oldBuf);
  web_delete_buffer(myBuf);
  webloc = tpos;
}

void lemur::parse::WebParser::doParse() {

  int tok;

  // The core loop of the parser.
  // The parser is state based.  Encountering a tag
  // can transition the machine into another state.
  // When in the DOC state, text is parsed.
  while (tok = weblex()) {
    switch (tok) {

    case E_DOC:
      state = OUTER;
      if (textHandler != NULL) textHandler->foundEndDoc();
      break;
    
    case B_DOC:
      docpos = webloc - webleng;
      state = DOC;
      break;

    case F_DOCNO:
      {
        // Extract the document number and pass it on.
	char * dn = webtext + 7;
	while (isspace(*dn)) dn++;
	char * de = dn;
	while (!isspace(*de) && *de != '<') de++;
	*de = '\0';
	if (textHandler != NULL) textHandler->foundDoc(dn);

	state = DOC;
	break;
      }

    case B_DOCHDR:
      // DOCHDRs are ignored
      state = DOCHDR;
      break;

    case E_DOCHDR:
      state = DOC;
      break;

    case B_DOCOLDNO:
      // DOCOLDNOs are ignored
      state = DOCOLDNO;
      break;

    case E_DOCOLDNO:
      state = DOC;
      break;

    case B_COMMENT:
      // Comments are ignored
      // Can only transition to the COMMENT state if in the DOC state,
      // handling comments within script tags appropriately.
      if (state == DOC)
        state = COMMENT;
      break;

    case E_COMMENT:
      if (state == COMMENT)
        state = DOC;
      break;

    case B_SCRIPT:
      // Script fields are ignored
      // Can only transition to a SCRIPT state if in the DOC state,
      // handling script tags within comment tags appropriately.
      if (state == DOC)
        state = SCRIPT;
      break;

    case E_SCRIPT:
      if (state == SCRIPT)
        state = DOC;
      break;
         
    case B_STYLE:
      // Style fields are ignored
      // Can only transition to a STYLE state if in the DOC state,
      // handling style tags within comment tags appropriately.
      if (state == DOC)
        state = STYLE;
      break;

    case E_STYLE:
      if (state == STYLE)
        state = DOC;
      break;

    case B_TITLE:
      // title words should be indexed
      state = DOC;
      
      begelem.setValue("TITLE");
      proplist.clear();
      proplist.setProperty(&begelem);
      if (textHandler)
        textHandler->foundToken(BEGINTAG, webtext, webtext, &proplist);
      break;

    case E_TITLE:
      state = DOC;
      endelem.setValue("TITLE");
      proplist.clear();
      proplist.setProperty(&endelem);
      if (textHandler)
        textHandler->foundToken(ENDTAG, webtext, webtext, &proplist);
      break;

    case B_DATE:
      // state = DOC;
      begelem.setValue("DATE");
      proplist.clear();
      proplist.setProperty(&begelem);
      if (textHandler)
        textHandler->foundToken(BEGINTAG, webtext, webtext, &proplist);
      break;

    case E_DATE:
      // state = DOC;
      endelem.setValue("DATE");
      proplist.clear();
      proplist.setProperty(&endelem);
      if (textHandler)
        textHandler->foundToken(ENDTAG, webtext, webtext, &proplist);
      break;
     
    case WORD:
      if (state == DOC) {
        // put the word in lowercase and pass it on
	for (char * c = webtext; *c != '\0'; c++)
	  *(c) = tolower(*c);
	if (textHandler != NULL) textHandler->foundWord(webtext);
      }
      break;

    case CONTRACTION:
      if (state == DOC) {
        // strip the suffx, put the word in lowercase, pass it on
	char * c;
	int len = 0, diff;
	for (c = webtext; *c != '\''; c++, len++)
	  *(c) = tolower(*c);	
        *c = '\0';
	diff = webleng - len;
	webloc -= diff; /* change endpoint for docMgr usage. */
	if (textHandler != NULL) textHandler->foundWord(webtext);
	webloc += diff;
	c++;
	if (textHandler != NULL) textHandler->foundWord(c);
      }
      break;

    case UPWORD:
      if (state == DOC) {
        if (! isAcronym(webtext)) {
	  // put in lowercase if the word is not in the acronym list
	  for (char * c = webtext; *c != '\0'; c++)
	    *(c) = tolower(*c);
	}
	if (textHandler != NULL) textHandler->foundWord(webtext);	
      }
      break;

    case ACRONYM:
      if (state == DOC) {
	char * e = webtext;
	// strip periods
	for (char * c = webtext; *c != '\0'; c++) {
	  if (*c != '.') *(e++) = *c;
	}
	*e = '\0';
	if (!isAcronym(webtext)) {
	  // put in lowercase if the word is not in the acronym list
	  for (char * c = webtext; *c != '\0'; c++)
	    *(c) = tolower(*c);	 
	}
	if (textHandler != NULL) textHandler->foundWord(webtext);
      }
      break;
    
    case ACRONYM2:
      if (state == DOC) {
        char * c;
	int len = 0, diff;
	// strip the suffix
	for (c = webtext; *c != '\'' && *c != '\0' && *c != 's'; c++, len++);
        *c = '\0';
	if (!isAcronym(webtext)) {
	  // put in lowercase if the word is not in the acronym list
	  for (c = webtext; *c != '\0'; c++)
	    *(c) = tolower(*c);	 
	}
	diff = webleng - len;
	webloc -= diff; /* change endpoint for docMgr usage. */
	if (textHandler != NULL) textHandler->foundWord(webtext);
	webloc += diff;
      }      
      break;

    }

  }
}


