/* soapH.h
   Generated by the gSOAP Stub and Skeleton Compiler for C and C++ 2.1.3b
   Copyright (C) 2001-2002 Robert A. van Engelen, Florida State University.
   All rights reserved.
*/
#ifndef soapH_H
#define soapH_H
#include "stdsoap2.h"
#include "soapStub.h"

#ifndef SOAP_byte
#define SOAP_byte (1)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_byte(struct soap*, char const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_byte(char *);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC1 char * SOAP_FMAC2 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC1 char * SOAP_FMAC2 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_xsd__int
#define SOAP_xsd__int (2)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsd__int(struct soap*, int const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsd__int(int *);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_xsd__int(struct soap*, int *, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_xsd__int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC1 int * SOAP_FMAC2 soap_get_xsd__int(struct soap*, int *, const char*, const char*);
SOAP_FMAC1 int * SOAP_FMAC2 soap_in_xsd__int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_int
#define SOAP_int (3)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_int(struct soap*, int const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_int(int *);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC1 int * SOAP_FMAC2 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC1 int * SOAP_FMAC2 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_xsd__double
#define SOAP_xsd__double (4)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsd__double(struct soap*, double const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsd__double(double *);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_xsd__double(struct soap*, double *, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_xsd__double(struct soap*, const char*, int, const double *, const char*);
SOAP_FMAC1 double * SOAP_FMAC2 soap_get_xsd__double(struct soap*, double *, const char*, const char*);
SOAP_FMAC1 double * SOAP_FMAC2 soap_in_xsd__double(struct soap*, const char*, double *, const char*);

#ifndef SOAP_double
#define SOAP_double (5)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_double(struct soap*, double const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_double(double *);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_double(struct soap*, double *, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_double(struct soap*, const char*, int, const double *, const char*);
SOAP_FMAC1 double * SOAP_FMAC2 soap_get_double(struct soap*, double *, const char*, const char*);
SOAP_FMAC1 double * SOAP_FMAC2 soap_in_double(struct soap*, const char*, double *, const char*);

#ifndef SOAP_xsd__boolean
#define SOAP_xsd__boolean (6)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsd__boolean(struct soap*, bool const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsd__boolean(bool *);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_xsd__boolean(struct soap*, bool *, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_xsd__boolean(struct soap*, const char*, int, const bool *, const char*);
SOAP_FMAC1 bool * SOAP_FMAC2 soap_get_xsd__boolean(struct soap*, bool *, const char*, const char*);
SOAP_FMAC1 bool * SOAP_FMAC2 soap_in_xsd__boolean(struct soap*, const char*, bool *, const char*);

#ifndef SOAP_bool
#define SOAP_bool (7)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_bool(struct soap*, bool const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_bool(bool *);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_bool(struct soap*, bool *, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_bool(struct soap*, const char*, int, const bool *, const char*);
SOAP_FMAC1 bool * SOAP_FMAC2 soap_get_bool(struct soap*, bool *, const char*, const char*);
SOAP_FMAC1 bool * SOAP_FMAC2 soap_in_bool(struct soap*, const char*, bool *, const char*);

#ifndef SOAP_mindcall__constructResourceDescriptionResponse
#define SOAP_mindcall__constructResourceDescriptionResponse (8)
#endif

SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindcall__constructResourceDescriptionResponse(struct soap*, const char*, int, const mindcall__constructResourceDescriptionResponse *, const char*);
SOAP_FMAC1 mindcall__constructResourceDescriptionResponse * SOAP_FMAC2 soap_get_mindcall__constructResourceDescriptionResponse(struct soap*, mindcall__constructResourceDescriptionResponse *, const char*, const char*);
SOAP_FMAC1 mindcall__constructResourceDescriptionResponse * SOAP_FMAC2 soap_in_mindcall__constructResourceDescriptionResponse(struct soap*, const char*, mindcall__constructResourceDescriptionResponse *, const char*);

#define soap_new_mindcall__constructResourceDescriptionResponse(soap, n) soap_instantiate_mindcall__constructResourceDescriptionResponse(soap, n, NULL, NULL);

SOAP_FMAC1 mindcall__constructResourceDescriptionResponse * SOAP_FMAC2 soap_instantiate_mindcall__constructResourceDescriptionResponse(struct soap*, int, const char*, const char*);

#ifndef SOAP_mindcall__addDocumentResponse
#define SOAP_mindcall__addDocumentResponse (9)
#endif

SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindcall__addDocumentResponse(struct soap*, const char*, int, const mindcall__addDocumentResponse *, const char*);
SOAP_FMAC1 mindcall__addDocumentResponse * SOAP_FMAC2 soap_get_mindcall__addDocumentResponse(struct soap*, mindcall__addDocumentResponse *, const char*, const char*);
SOAP_FMAC1 mindcall__addDocumentResponse * SOAP_FMAC2 soap_in_mindcall__addDocumentResponse(struct soap*, const char*, mindcall__addDocumentResponse *, const char*);

#define soap_new_mindcall__addDocumentResponse(soap, n) soap_instantiate_mindcall__addDocumentResponse(soap, n, NULL, NULL);

SOAP_FMAC1 mindcall__addDocumentResponse * SOAP_FMAC2 soap_instantiate_mindcall__addDocumentResponse(struct soap*, int, const char*, const char*);

#ifndef SOAP_mindcall__clearDocumentsResponse
#define SOAP_mindcall__clearDocumentsResponse (10)
#endif

SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindcall__clearDocumentsResponse(struct soap*, const char*, int, const mindcall__clearDocumentsResponse *, const char*);
SOAP_FMAC1 mindcall__clearDocumentsResponse * SOAP_FMAC2 soap_get_mindcall__clearDocumentsResponse(struct soap*, mindcall__clearDocumentsResponse *, const char*, const char*);
SOAP_FMAC1 mindcall__clearDocumentsResponse * SOAP_FMAC2 soap_in_mindcall__clearDocumentsResponse(struct soap*, const char*, mindcall__clearDocumentsResponse *, const char*);

#define soap_new_mindcall__clearDocumentsResponse(soap, n) soap_instantiate_mindcall__clearDocumentsResponse(soap, n, NULL, NULL);

SOAP_FMAC1 mindcall__clearDocumentsResponse * SOAP_FMAC2 soap_instantiate_mindcall__clearDocumentsResponse(struct soap*, int, const char*, const char*);

#ifndef SOAP_mindcall__setCollectionNumDocsResponse
#define SOAP_mindcall__setCollectionNumDocsResponse (11)
#endif

SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindcall__setCollectionNumDocsResponse(struct soap*, const char*, int, const mindcall__setCollectionNumDocsResponse *, const char*);
SOAP_FMAC1 mindcall__setCollectionNumDocsResponse * SOAP_FMAC2 soap_get_mindcall__setCollectionNumDocsResponse(struct soap*, mindcall__setCollectionNumDocsResponse *, const char*, const char*);
SOAP_FMAC1 mindcall__setCollectionNumDocsResponse * SOAP_FMAC2 soap_in_mindcall__setCollectionNumDocsResponse(struct soap*, const char*, mindcall__setCollectionNumDocsResponse *, const char*);

#define soap_new_mindcall__setCollectionNumDocsResponse(soap, n) soap_instantiate_mindcall__setCollectionNumDocsResponse(soap, n, NULL, NULL);

SOAP_FMAC1 mindcall__setCollectionNumDocsResponse * SOAP_FMAC2 soap_instantiate_mindcall__setCollectionNumDocsResponse(struct soap*, int, const char*, const char*);

#ifndef SOAP_mindcall__getSchemaResponse
#define SOAP_mindcall__getSchemaResponse (12)
#endif

SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindcall__getSchemaResponse(struct soap*, const char*, int, const mindcall__getSchemaResponse *, const char*);
SOAP_FMAC1 mindcall__getSchemaResponse * SOAP_FMAC2 soap_get_mindcall__getSchemaResponse(struct soap*, mindcall__getSchemaResponse *, const char*, const char*);
SOAP_FMAC1 mindcall__getSchemaResponse * SOAP_FMAC2 soap_in_mindcall__getSchemaResponse(struct soap*, const char*, mindcall__getSchemaResponse *, const char*);

#define soap_new_mindcall__getSchemaResponse(soap, n) soap_instantiate_mindcall__getSchemaResponse(soap, n, NULL, NULL);

SOAP_FMAC1 mindcall__getSchemaResponse * SOAP_FMAC2 soap_instantiate_mindcall__getSchemaResponse(struct soap*, int, const char*, const char*);

#ifndef SOAP_mindcall__extractQBSFeaturesResponse
#define SOAP_mindcall__extractQBSFeaturesResponse (13)
#endif

SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindcall__extractQBSFeaturesResponse(struct soap*, const char*, int, const mindcall__extractQBSFeaturesResponse *, const char*);
SOAP_FMAC1 mindcall__extractQBSFeaturesResponse * SOAP_FMAC2 soap_get_mindcall__extractQBSFeaturesResponse(struct soap*, mindcall__extractQBSFeaturesResponse *, const char*, const char*);
SOAP_FMAC1 mindcall__extractQBSFeaturesResponse * SOAP_FMAC2 soap_in_mindcall__extractQBSFeaturesResponse(struct soap*, const char*, mindcall__extractQBSFeaturesResponse *, const char*);

#define soap_new_mindcall__extractQBSFeaturesResponse(soap, n) soap_instantiate_mindcall__extractQBSFeaturesResponse(soap, n, NULL, NULL);

SOAP_FMAC1 mindcall__extractQBSFeaturesResponse * SOAP_FMAC2 soap_instantiate_mindcall__extractQBSFeaturesResponse(struct soap*, int, const char*, const char*);

#ifndef SOAP_mindtype__FeatureList
#define SOAP_mindtype__FeatureList (14)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindtype__FeatureList(struct soap*, const char*, int, const mindtype__FeatureList *, const char*);
SOAP_FMAC1 mindtype__FeatureList * SOAP_FMAC2 soap_get_mindtype__FeatureList(struct soap*, mindtype__FeatureList *, const char*, const char*);
SOAP_FMAC1 mindtype__FeatureList * SOAP_FMAC2 soap_in_mindtype__FeatureList(struct soap*, const char*, mindtype__FeatureList *, const char*);

#define soap_new_mindtype__FeatureList(soap, n) soap_instantiate_mindtype__FeatureList(soap, n, NULL, NULL);

SOAP_FMAC1 mindtype__FeatureList * SOAP_FMAC2 soap_instantiate_mindtype__FeatureList(struct soap*, int, const char*, const char*);

#ifndef SOAP_mindcall__queryResponse
#define SOAP_mindcall__queryResponse (15)
#endif

SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindcall__queryResponse(struct soap*, const char*, int, const mindcall__queryResponse *, const char*);
SOAP_FMAC1 mindcall__queryResponse * SOAP_FMAC2 soap_get_mindcall__queryResponse(struct soap*, mindcall__queryResponse *, const char*, const char*);
SOAP_FMAC1 mindcall__queryResponse * SOAP_FMAC2 soap_in_mindcall__queryResponse(struct soap*, const char*, mindcall__queryResponse *, const char*);

#define soap_new_mindcall__queryResponse(soap, n) soap_instantiate_mindcall__queryResponse(soap, n, NULL, NULL);

SOAP_FMAC1 mindcall__queryResponse * SOAP_FMAC2 soap_instantiate_mindcall__queryResponse(struct soap*, int, const char*, const char*);

#ifndef SOAP_mindtype__PropResult
#define SOAP_mindtype__PropResult (16)
#endif

SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindtype__PropResult(struct soap*, const char*, int, const mindtype__PropResult *, const char*);
SOAP_FMAC1 mindtype__PropResult * SOAP_FMAC2 soap_get_mindtype__PropResult(struct soap*, mindtype__PropResult *, const char*, const char*);
SOAP_FMAC1 mindtype__PropResult * SOAP_FMAC2 soap_in_mindtype__PropResult(struct soap*, const char*, mindtype__PropResult *, const char*);

#define soap_new_mindtype__PropResult(soap, n) soap_instantiate_mindtype__PropResult(soap, n, NULL, NULL);

SOAP_FMAC1 mindtype__PropResult * SOAP_FMAC2 soap_instantiate_mindtype__PropResult(struct soap*, int, const char*, const char*);

#ifndef SOAP_mindtype__PropDocumentArray
#define SOAP_mindtype__PropDocumentArray (17)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindtype__PropDocumentArray(struct soap*, const char*, int, const mindtype__PropDocumentArray *, const char*);
SOAP_FMAC1 mindtype__PropDocumentArray * SOAP_FMAC2 soap_get_mindtype__PropDocumentArray(struct soap*, mindtype__PropDocumentArray *, const char*, const char*);
SOAP_FMAC1 mindtype__PropDocumentArray * SOAP_FMAC2 soap_in_mindtype__PropDocumentArray(struct soap*, const char*, mindtype__PropDocumentArray *, const char*);

#define soap_new_mindtype__PropDocumentArray(soap, n) soap_instantiate_mindtype__PropDocumentArray(soap, n, NULL, NULL);

SOAP_FMAC1 mindtype__PropDocumentArray * SOAP_FMAC2 soap_instantiate_mindtype__PropDocumentArray(struct soap*, int, const char*, const char*);

#ifndef SOAP_mindtype__PropDocument
#define SOAP_mindtype__PropDocument (18)
#endif

SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindtype__PropDocument(struct soap*, const char*, int, const mindtype__PropDocument *, const char*);
SOAP_FMAC1 mindtype__PropDocument * SOAP_FMAC2 soap_get_mindtype__PropDocument(struct soap*, mindtype__PropDocument *, const char*, const char*);
SOAP_FMAC1 mindtype__PropDocument * SOAP_FMAC2 soap_in_mindtype__PropDocument(struct soap*, const char*, mindtype__PropDocument *, const char*);

#define soap_new_mindtype__PropDocument(soap, n) soap_instantiate_mindtype__PropDocument(soap, n, NULL, NULL);

SOAP_FMAC1 mindtype__PropDocument * SOAP_FMAC2 soap_instantiate_mindtype__PropDocument(struct soap*, int, const char*, const char*);

#ifndef SOAP_mindtype__PropDocumentAttributeArray
#define SOAP_mindtype__PropDocumentAttributeArray (19)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindtype__PropDocumentAttributeArray(struct soap*, const char*, int, const mindtype__PropDocumentAttributeArray *, const char*);
SOAP_FMAC1 mindtype__PropDocumentAttributeArray * SOAP_FMAC2 soap_get_mindtype__PropDocumentAttributeArray(struct soap*, mindtype__PropDocumentAttributeArray *, const char*, const char*);
SOAP_FMAC1 mindtype__PropDocumentAttributeArray * SOAP_FMAC2 soap_in_mindtype__PropDocumentAttributeArray(struct soap*, const char*, mindtype__PropDocumentAttributeArray *, const char*);

#define soap_new_mindtype__PropDocumentAttributeArray(soap, n) soap_instantiate_mindtype__PropDocumentAttributeArray(soap, n, NULL, NULL);

SOAP_FMAC1 mindtype__PropDocumentAttributeArray * SOAP_FMAC2 soap_instantiate_mindtype__PropDocumentAttributeArray(struct soap*, int, const char*, const char*);

#ifndef SOAP_mindtype__PropDocumentAttribute
#define SOAP_mindtype__PropDocumentAttribute (20)
#endif

SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindtype__PropDocumentAttribute(struct soap*, const char*, int, const mindtype__PropDocumentAttribute *, const char*);
SOAP_FMAC1 mindtype__PropDocumentAttribute * SOAP_FMAC2 soap_get_mindtype__PropDocumentAttribute(struct soap*, mindtype__PropDocumentAttribute *, const char*, const char*);
SOAP_FMAC1 mindtype__PropDocumentAttribute * SOAP_FMAC2 soap_in_mindtype__PropDocumentAttribute(struct soap*, const char*, mindtype__PropDocumentAttribute *, const char*);

#define soap_new_mindtype__PropDocumentAttribute(soap, n) soap_instantiate_mindtype__PropDocumentAttribute(soap, n, NULL, NULL);

SOAP_FMAC1 mindtype__PropDocumentAttribute * SOAP_FMAC2 soap_instantiate_mindtype__PropDocumentAttribute(struct soap*, int, const char*, const char*);

#ifndef SOAP_mindtype__DocumentID
#define SOAP_mindtype__DocumentID (21)
#endif

SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindtype__DocumentID(struct soap*, const char*, int, const mindtype__DocumentID *, const char*);
SOAP_FMAC1 mindtype__DocumentID * SOAP_FMAC2 soap_get_mindtype__DocumentID(struct soap*, mindtype__DocumentID *, const char*, const char*);
SOAP_FMAC1 mindtype__DocumentID * SOAP_FMAC2 soap_in_mindtype__DocumentID(struct soap*, const char*, mindtype__DocumentID *, const char*);

#define soap_new_mindtype__DocumentID(soap, n) soap_instantiate_mindtype__DocumentID(soap, n, NULL, NULL);

SOAP_FMAC1 mindtype__DocumentID * SOAP_FMAC2 soap_instantiate_mindtype__DocumentID(struct soap*, int, const char*, const char*);

#ifndef SOAP_mindtype__SchemaArray
#define SOAP_mindtype__SchemaArray (22)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindtype__SchemaArray(struct soap*, const char*, int, const mindtype__SchemaArray *, const char*);
SOAP_FMAC1 mindtype__SchemaArray * SOAP_FMAC2 soap_get_mindtype__SchemaArray(struct soap*, mindtype__SchemaArray *, const char*, const char*);
SOAP_FMAC1 mindtype__SchemaArray * SOAP_FMAC2 soap_in_mindtype__SchemaArray(struct soap*, const char*, mindtype__SchemaArray *, const char*);

#define soap_new_mindtype__SchemaArray(soap, n) soap_instantiate_mindtype__SchemaArray(soap, n, NULL, NULL);

SOAP_FMAC1 mindtype__SchemaArray * SOAP_FMAC2 soap_instantiate_mindtype__SchemaArray(struct soap*, int, const char*, const char*);

#ifndef SOAP_mindtype__PropQuery
#define SOAP_mindtype__PropQuery (23)
#endif

SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindtype__PropQuery(struct soap*, const char*, int, const mindtype__PropQuery *, const char*);
SOAP_FMAC1 mindtype__PropQuery * SOAP_FMAC2 soap_get_mindtype__PropQuery(struct soap*, mindtype__PropQuery *, const char*, const char*);
SOAP_FMAC1 mindtype__PropQuery * SOAP_FMAC2 soap_in_mindtype__PropQuery(struct soap*, const char*, mindtype__PropQuery *, const char*);

#define soap_new_mindtype__PropQuery(soap, n) soap_instantiate_mindtype__PropQuery(soap, n, NULL, NULL);

SOAP_FMAC1 mindtype__PropQuery * SOAP_FMAC2 soap_instantiate_mindtype__PropQuery(struct soap*, int, const char*, const char*);

#ifndef SOAP_PropQueryConditionArray
#define SOAP_PropQueryConditionArray (24)
#endif

SOAP_FMAC1 void SOAP_FMAC2 soap_out_PropQueryConditionArray(struct soap*, const char*, int, const PropQueryConditionArray *, const char*);
SOAP_FMAC1 PropQueryConditionArray * SOAP_FMAC2 soap_get_PropQueryConditionArray(struct soap*, PropQueryConditionArray *, const char*, const char*);
SOAP_FMAC1 PropQueryConditionArray * SOAP_FMAC2 soap_in_PropQueryConditionArray(struct soap*, const char*, PropQueryConditionArray *, const char*);

#define soap_new_PropQueryConditionArray(soap, n) soap_instantiate_PropQueryConditionArray(soap, n, NULL, NULL);

SOAP_FMAC1 PropQueryConditionArray * SOAP_FMAC2 soap_instantiate_PropQueryConditionArray(struct soap*, int, const char*, const char*);

#ifndef SOAP_mindtype__PropQueryCondition
#define SOAP_mindtype__PropQueryCondition (25)
#endif

SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindtype__PropQueryCondition(struct soap*, const char*, int, const mindtype__PropQueryCondition *, const char*);
SOAP_FMAC1 mindtype__PropQueryCondition * SOAP_FMAC2 soap_get_mindtype__PropQueryCondition(struct soap*, mindtype__PropQueryCondition *, const char*, const char*);
SOAP_FMAC1 mindtype__PropQueryCondition * SOAP_FMAC2 soap_in_mindtype__PropQueryCondition(struct soap*, const char*, mindtype__PropQueryCondition *, const char*);

#define soap_new_mindtype__PropQueryCondition(soap, n) soap_instantiate_mindtype__PropQueryCondition(soap, n, NULL, NULL);

SOAP_FMAC1 mindtype__PropQueryCondition * SOAP_FMAC2 soap_instantiate_mindtype__PropQueryCondition(struct soap*, int, const char*, const char*);

#ifndef SOAP_mindtype__Content
#define SOAP_mindtype__Content (26)
#endif

SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindtype__Content(struct soap*, const char*, int, const mindtype__Content *, const char*);
SOAP_FMAC1 mindtype__Content * SOAP_FMAC2 soap_get_mindtype__Content(struct soap*, mindtype__Content *, const char*, const char*);
SOAP_FMAC1 mindtype__Content * SOAP_FMAC2 soap_in_mindtype__Content(struct soap*, const char*, mindtype__Content *, const char*);

#define soap_new_mindtype__Content(soap, n) soap_instantiate_mindtype__Content(soap, n, NULL, NULL);

SOAP_FMAC1 mindtype__Content * SOAP_FMAC2 soap_instantiate_mindtype__Content(struct soap*, int, const char*, const char*);

#ifndef SOAP_mindtype__CostParameters
#define SOAP_mindtype__CostParameters (27)
#endif

SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindtype__CostParameters(struct soap*, const char*, int, const mindtype__CostParameters *, const char*);
SOAP_FMAC1 mindtype__CostParameters * SOAP_FMAC2 soap_get_mindtype__CostParameters(struct soap*, mindtype__CostParameters *, const char*, const char*);
SOAP_FMAC1 mindtype__CostParameters * SOAP_FMAC2 soap_in_mindtype__CostParameters(struct soap*, const char*, mindtype__CostParameters *, const char*);

#define soap_new_mindtype__CostParameters(soap, n) soap_instantiate_mindtype__CostParameters(soap, n, NULL, NULL);

SOAP_FMAC1 mindtype__CostParameters * SOAP_FMAC2 soap_instantiate_mindtype__CostParameters(struct soap*, int, const char*, const char*);

#ifndef SOAP_mindtype__Query
#define SOAP_mindtype__Query (28)
#endif

SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindtype__Query(struct soap*, const char*, int, const mindtype__Query *, const char*);
SOAP_FMAC1 mindtype__Query * SOAP_FMAC2 soap_get_mindtype__Query(struct soap*, mindtype__Query *, const char*, const char*);
SOAP_FMAC1 mindtype__Query * SOAP_FMAC2 soap_in_mindtype__Query(struct soap*, const char*, mindtype__Query *, const char*);

#define soap_new_mindtype__Query(soap, n) soap_instantiate_mindtype__Query(soap, n, NULL, NULL);

SOAP_FMAC1 mindtype__Query * SOAP_FMAC2 soap_instantiate_mindtype__Query(struct soap*, int, const char*, const char*);

#ifndef SOAP_mindtype__Schema
#define SOAP_mindtype__Schema (29)
#endif

SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindtype__Schema(struct soap*, const char*, int, const mindtype__Schema *, const char*);
SOAP_FMAC1 mindtype__Schema * SOAP_FMAC2 soap_get_mindtype__Schema(struct soap*, mindtype__Schema *, const char*, const char*);
SOAP_FMAC1 mindtype__Schema * SOAP_FMAC2 soap_in_mindtype__Schema(struct soap*, const char*, mindtype__Schema *, const char*);

#define soap_new_mindtype__Schema(soap, n) soap_instantiate_mindtype__Schema(soap, n, NULL, NULL);

SOAP_FMAC1 mindtype__Schema * SOAP_FMAC2 soap_instantiate_mindtype__Schema(struct soap*, int, const char*, const char*);

#ifndef SOAP_SchemaAttributeArray
#define SOAP_SchemaAttributeArray (30)
#endif

SOAP_FMAC1 void SOAP_FMAC2 soap_out_SchemaAttributeArray(struct soap*, const char*, int, const SchemaAttributeArray *, const char*);
SOAP_FMAC1 SchemaAttributeArray * SOAP_FMAC2 soap_get_SchemaAttributeArray(struct soap*, SchemaAttributeArray *, const char*, const char*);
SOAP_FMAC1 SchemaAttributeArray * SOAP_FMAC2 soap_in_SchemaAttributeArray(struct soap*, const char*, SchemaAttributeArray *, const char*);

#define soap_new_SchemaAttributeArray(soap, n) soap_instantiate_SchemaAttributeArray(soap, n, NULL, NULL);

SOAP_FMAC1 SchemaAttributeArray * SOAP_FMAC2 soap_instantiate_SchemaAttributeArray(struct soap*, int, const char*, const char*);

#ifndef SOAP_mindtype__SchemaAttribute
#define SOAP_mindtype__SchemaAttribute (31)
#endif

SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindtype__SchemaAttribute(struct soap*, const char*, int, const mindtype__SchemaAttribute *, const char*);
SOAP_FMAC1 mindtype__SchemaAttribute * SOAP_FMAC2 soap_get_mindtype__SchemaAttribute(struct soap*, mindtype__SchemaAttribute *, const char*, const char*);
SOAP_FMAC1 mindtype__SchemaAttribute * SOAP_FMAC2 soap_in_mindtype__SchemaAttribute(struct soap*, const char*, mindtype__SchemaAttribute *, const char*);

#define soap_new_mindtype__SchemaAttribute(soap, n) soap_instantiate_mindtype__SchemaAttribute(soap, n, NULL, NULL);

SOAP_FMAC1 mindtype__SchemaAttribute * SOAP_FMAC2 soap_instantiate_mindtype__SchemaAttribute(struct soap*, int, const char*, const char*);

#ifndef SOAP_PredicateArray
#define SOAP_PredicateArray (32)
#endif

SOAP_FMAC1 void SOAP_FMAC2 soap_out_PredicateArray(struct soap*, const char*, int, const PredicateArray *, const char*);
SOAP_FMAC1 PredicateArray * SOAP_FMAC2 soap_get_PredicateArray(struct soap*, PredicateArray *, const char*, const char*);
SOAP_FMAC1 PredicateArray * SOAP_FMAC2 soap_in_PredicateArray(struct soap*, const char*, PredicateArray *, const char*);

#define soap_new_PredicateArray(soap, n) soap_instantiate_PredicateArray(soap, n, NULL, NULL);

SOAP_FMAC1 PredicateArray * SOAP_FMAC2 soap_instantiate_PredicateArray(struct soap*, int, const char*, const char*);

#ifndef SOAP_SOAP_ENV__Fault
#define SOAP_SOAP_ENV__Fault (33)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_SOAP_ENV__Fault(struct SOAP_ENV__Fault *);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#ifndef SOAP_SOAP_ENV__Header
#define SOAP_SOAP_ENV__Header (34)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_SOAP_ENV__Header(struct SOAP_ENV__Header *);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#ifndef SOAP_mindcall__constructResourceDescription
#define SOAP_mindcall__constructResourceDescription (35)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_mindcall__constructResourceDescription(struct soap*, struct mindcall__constructResourceDescription const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_mindcall__constructResourceDescription(struct soap*, const struct mindcall__constructResourceDescription *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_mindcall__constructResourceDescription(struct mindcall__constructResourceDescription *);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_mindcall__constructResourceDescription(struct soap*, struct mindcall__constructResourceDescription *, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindcall__constructResourceDescription(struct soap*, const char*, int, const struct mindcall__constructResourceDescription *, const char*);
SOAP_FMAC1 struct mindcall__constructResourceDescription * SOAP_FMAC2 soap_get_mindcall__constructResourceDescription(struct soap*, struct mindcall__constructResourceDescription *, const char*, const char*);
SOAP_FMAC1 struct mindcall__constructResourceDescription * SOAP_FMAC2 soap_in_mindcall__constructResourceDescription(struct soap*, const char*, struct mindcall__constructResourceDescription *, const char*);

#ifndef SOAP_mindcall__addDocument
#define SOAP_mindcall__addDocument (36)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_mindcall__addDocument(struct soap*, struct mindcall__addDocument const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_mindcall__addDocument(struct soap*, const struct mindcall__addDocument *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_mindcall__addDocument(struct mindcall__addDocument *);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_mindcall__addDocument(struct soap*, struct mindcall__addDocument *, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindcall__addDocument(struct soap*, const char*, int, const struct mindcall__addDocument *, const char*);
SOAP_FMAC1 struct mindcall__addDocument * SOAP_FMAC2 soap_get_mindcall__addDocument(struct soap*, struct mindcall__addDocument *, const char*, const char*);
SOAP_FMAC1 struct mindcall__addDocument * SOAP_FMAC2 soap_in_mindcall__addDocument(struct soap*, const char*, struct mindcall__addDocument *, const char*);

#ifndef SOAP_mindcall__clearDocuments
#define SOAP_mindcall__clearDocuments (37)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_mindcall__clearDocuments(struct soap*, struct mindcall__clearDocuments const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_mindcall__clearDocuments(struct soap*, const struct mindcall__clearDocuments *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_mindcall__clearDocuments(struct mindcall__clearDocuments *);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_mindcall__clearDocuments(struct soap*, struct mindcall__clearDocuments *, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindcall__clearDocuments(struct soap*, const char*, int, const struct mindcall__clearDocuments *, const char*);
SOAP_FMAC1 struct mindcall__clearDocuments * SOAP_FMAC2 soap_get_mindcall__clearDocuments(struct soap*, struct mindcall__clearDocuments *, const char*, const char*);
SOAP_FMAC1 struct mindcall__clearDocuments * SOAP_FMAC2 soap_in_mindcall__clearDocuments(struct soap*, const char*, struct mindcall__clearDocuments *, const char*);

#ifndef SOAP_mindcall__setCollectionNumDocs
#define SOAP_mindcall__setCollectionNumDocs (38)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_mindcall__setCollectionNumDocs(struct soap*, struct mindcall__setCollectionNumDocs const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_mindcall__setCollectionNumDocs(struct soap*, const struct mindcall__setCollectionNumDocs *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_mindcall__setCollectionNumDocs(struct mindcall__setCollectionNumDocs *);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_mindcall__setCollectionNumDocs(struct soap*, struct mindcall__setCollectionNumDocs *, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindcall__setCollectionNumDocs(struct soap*, const char*, int, const struct mindcall__setCollectionNumDocs *, const char*);
SOAP_FMAC1 struct mindcall__setCollectionNumDocs * SOAP_FMAC2 soap_get_mindcall__setCollectionNumDocs(struct soap*, struct mindcall__setCollectionNumDocs *, const char*, const char*);
SOAP_FMAC1 struct mindcall__setCollectionNumDocs * SOAP_FMAC2 soap_in_mindcall__setCollectionNumDocs(struct soap*, const char*, struct mindcall__setCollectionNumDocs *, const char*);

#ifndef SOAP_mindcall__getSchema
#define SOAP_mindcall__getSchema (39)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_mindcall__getSchema(struct soap*, struct mindcall__getSchema const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_mindcall__getSchema(struct soap*, const struct mindcall__getSchema *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_mindcall__getSchema(struct mindcall__getSchema *);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_mindcall__getSchema(struct soap*, struct mindcall__getSchema *, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindcall__getSchema(struct soap*, const char*, int, const struct mindcall__getSchema *, const char*);
SOAP_FMAC1 struct mindcall__getSchema * SOAP_FMAC2 soap_get_mindcall__getSchema(struct soap*, struct mindcall__getSchema *, const char*, const char*);
SOAP_FMAC1 struct mindcall__getSchema * SOAP_FMAC2 soap_in_mindcall__getSchema(struct soap*, const char*, struct mindcall__getSchema *, const char*);

#ifndef SOAP_mindcall__extractQBSFeatures
#define SOAP_mindcall__extractQBSFeatures (40)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_mindcall__extractQBSFeatures(struct soap*, struct mindcall__extractQBSFeatures const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_mindcall__extractQBSFeatures(struct soap*, const struct mindcall__extractQBSFeatures *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_mindcall__extractQBSFeatures(struct mindcall__extractQBSFeatures *);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_mindcall__extractQBSFeatures(struct soap*, struct mindcall__extractQBSFeatures *, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindcall__extractQBSFeatures(struct soap*, const char*, int, const struct mindcall__extractQBSFeatures *, const char*);
SOAP_FMAC1 struct mindcall__extractQBSFeatures * SOAP_FMAC2 soap_get_mindcall__extractQBSFeatures(struct soap*, struct mindcall__extractQBSFeatures *, const char*, const char*);
SOAP_FMAC1 struct mindcall__extractQBSFeatures * SOAP_FMAC2 soap_in_mindcall__extractQBSFeatures(struct soap*, const char*, struct mindcall__extractQBSFeatures *, const char*);

#ifndef SOAP_mindcall__query
#define SOAP_mindcall__query (41)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_mindcall__query(struct soap*, struct mindcall__query const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_mindcall__query(struct soap*, const struct mindcall__query *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_mindcall__query(struct mindcall__query *);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_mindcall__query(struct soap*, struct mindcall__query *, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindcall__query(struct soap*, const char*, int, const struct mindcall__query *, const char*);
SOAP_FMAC1 struct mindcall__query * SOAP_FMAC2 soap_get_mindcall__query(struct soap*, struct mindcall__query *, const char*, const char*);
SOAP_FMAC1 struct mindcall__query * SOAP_FMAC2 soap_in_mindcall__query(struct soap*, const char*, struct mindcall__query *, const char*);

#ifndef SOAP_mindcall__retrieveURL
#define SOAP_mindcall__retrieveURL (42)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_mindcall__retrieveURL(struct soap*, struct mindcall__retrieveURL const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_mindcall__retrieveURL(struct soap*, const struct mindcall__retrieveURL *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_mindcall__retrieveURL(struct mindcall__retrieveURL *);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_mindcall__retrieveURL(struct soap*, struct mindcall__retrieveURL *, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindcall__retrieveURL(struct soap*, const char*, int, const struct mindcall__retrieveURL *, const char*);
SOAP_FMAC1 struct mindcall__retrieveURL * SOAP_FMAC2 soap_get_mindcall__retrieveURL(struct soap*, struct mindcall__retrieveURL *, const char*, const char*);
SOAP_FMAC1 struct mindcall__retrieveURL * SOAP_FMAC2 soap_in_mindcall__retrieveURL(struct soap*, const char*, struct mindcall__retrieveURL *, const char*);

#ifndef SOAP_mindcall__retrieveURLResponse
#define SOAP_mindcall__retrieveURLResponse (43)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_mindcall__retrieveURLResponse(struct soap*, struct mindcall__retrieveURLResponse const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_mindcall__retrieveURLResponse(struct soap*, const struct mindcall__retrieveURLResponse *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_mindcall__retrieveURLResponse(struct mindcall__retrieveURLResponse *);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_mindcall__retrieveURLResponse(struct soap*, struct mindcall__retrieveURLResponse *, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindcall__retrieveURLResponse(struct soap*, const char*, int, const struct mindcall__retrieveURLResponse *, const char*);
SOAP_FMAC1 struct mindcall__retrieveURLResponse * SOAP_FMAC2 soap_get_mindcall__retrieveURLResponse(struct soap*, struct mindcall__retrieveURLResponse *, const char*, const char*);
SOAP_FMAC1 struct mindcall__retrieveURLResponse * SOAP_FMAC2 soap_in_mindcall__retrieveURLResponse(struct soap*, const char*, struct mindcall__retrieveURLResponse *, const char*);

#ifndef SOAP_mindcall__getInternalStatus
#define SOAP_mindcall__getInternalStatus (44)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_mindcall__getInternalStatus(struct soap*, struct mindcall__getInternalStatus const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_mindcall__getInternalStatus(struct soap*, const struct mindcall__getInternalStatus *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_mindcall__getInternalStatus(struct mindcall__getInternalStatus *);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_mindcall__getInternalStatus(struct soap*, struct mindcall__getInternalStatus *, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindcall__getInternalStatus(struct soap*, const char*, int, const struct mindcall__getInternalStatus *, const char*);
SOAP_FMAC1 struct mindcall__getInternalStatus * SOAP_FMAC2 soap_get_mindcall__getInternalStatus(struct soap*, struct mindcall__getInternalStatus *, const char*, const char*);
SOAP_FMAC1 struct mindcall__getInternalStatus * SOAP_FMAC2 soap_in_mindcall__getInternalStatus(struct soap*, const char*, struct mindcall__getInternalStatus *, const char*);

#ifndef SOAP_mindcall__getInternalStatusResponse
#define SOAP_mindcall__getInternalStatusResponse (45)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_mindcall__getInternalStatusResponse(struct soap*, struct mindcall__getInternalStatusResponse const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_mindcall__getInternalStatusResponse(struct soap*, const struct mindcall__getInternalStatusResponse *);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_mindcall__getInternalStatusResponse(struct mindcall__getInternalStatusResponse *);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_mindcall__getInternalStatusResponse(struct soap*, struct mindcall__getInternalStatusResponse *, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_mindcall__getInternalStatusResponse(struct soap*, const char*, int, const struct mindcall__getInternalStatusResponse *, const char*);
SOAP_FMAC1 struct mindcall__getInternalStatusResponse * SOAP_FMAC2 soap_get_mindcall__getInternalStatusResponse(struct soap*, struct mindcall__getInternalStatusResponse *, const char*, const char*);
SOAP_FMAC1 struct mindcall__getInternalStatusResponse * SOAP_FMAC2 soap_in_mindcall__getInternalStatusResponse(struct soap*, const char*, struct mindcall__getInternalStatusResponse *, const char*);

#ifndef SOAP_PointerTomindcall__constructResourceDescriptionResponse
#define SOAP_PointerTomindcall__constructResourceDescriptionResponse (46)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTomindcall__constructResourceDescriptionResponse(struct soap*, mindcall__constructResourceDescriptionResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTomindcall__constructResourceDescriptionResponse(struct soap*, mindcall__constructResourceDescriptionResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTomindcall__constructResourceDescriptionResponse(mindcall__constructResourceDescriptionResponse **);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_PointerTomindcall__constructResourceDescriptionResponse(struct soap*, mindcall__constructResourceDescriptionResponse **, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_PointerTomindcall__constructResourceDescriptionResponse(struct soap*, const char *, int, mindcall__constructResourceDescriptionResponse *const*, const char *);
SOAP_FMAC1 mindcall__constructResourceDescriptionResponse ** SOAP_FMAC2 soap_get_PointerTomindcall__constructResourceDescriptionResponse(struct soap*, mindcall__constructResourceDescriptionResponse **, const char*, const char*);
SOAP_FMAC1 mindcall__constructResourceDescriptionResponse ** SOAP_FMAC2 soap_in_PointerTomindcall__constructResourceDescriptionResponse(struct soap*, const char*, mindcall__constructResourceDescriptionResponse **, const char*);

#ifndef SOAP_PointerTomindcall__addDocumentResponse
#define SOAP_PointerTomindcall__addDocumentResponse (47)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTomindcall__addDocumentResponse(struct soap*, mindcall__addDocumentResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTomindcall__addDocumentResponse(struct soap*, mindcall__addDocumentResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTomindcall__addDocumentResponse(mindcall__addDocumentResponse **);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_PointerTomindcall__addDocumentResponse(struct soap*, mindcall__addDocumentResponse **, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_PointerTomindcall__addDocumentResponse(struct soap*, const char *, int, mindcall__addDocumentResponse *const*, const char *);
SOAP_FMAC1 mindcall__addDocumentResponse ** SOAP_FMAC2 soap_get_PointerTomindcall__addDocumentResponse(struct soap*, mindcall__addDocumentResponse **, const char*, const char*);
SOAP_FMAC1 mindcall__addDocumentResponse ** SOAP_FMAC2 soap_in_PointerTomindcall__addDocumentResponse(struct soap*, const char*, mindcall__addDocumentResponse **, const char*);

#ifndef SOAP_PointerTomindcall__clearDocumentsResponse
#define SOAP_PointerTomindcall__clearDocumentsResponse (48)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTomindcall__clearDocumentsResponse(struct soap*, mindcall__clearDocumentsResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTomindcall__clearDocumentsResponse(struct soap*, mindcall__clearDocumentsResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTomindcall__clearDocumentsResponse(mindcall__clearDocumentsResponse **);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_PointerTomindcall__clearDocumentsResponse(struct soap*, mindcall__clearDocumentsResponse **, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_PointerTomindcall__clearDocumentsResponse(struct soap*, const char *, int, mindcall__clearDocumentsResponse *const*, const char *);
SOAP_FMAC1 mindcall__clearDocumentsResponse ** SOAP_FMAC2 soap_get_PointerTomindcall__clearDocumentsResponse(struct soap*, mindcall__clearDocumentsResponse **, const char*, const char*);
SOAP_FMAC1 mindcall__clearDocumentsResponse ** SOAP_FMAC2 soap_in_PointerTomindcall__clearDocumentsResponse(struct soap*, const char*, mindcall__clearDocumentsResponse **, const char*);

#ifndef SOAP_PointerTomindcall__setCollectionNumDocsResponse
#define SOAP_PointerTomindcall__setCollectionNumDocsResponse (49)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTomindcall__setCollectionNumDocsResponse(struct soap*, mindcall__setCollectionNumDocsResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTomindcall__setCollectionNumDocsResponse(struct soap*, mindcall__setCollectionNumDocsResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTomindcall__setCollectionNumDocsResponse(mindcall__setCollectionNumDocsResponse **);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_PointerTomindcall__setCollectionNumDocsResponse(struct soap*, mindcall__setCollectionNumDocsResponse **, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_PointerTomindcall__setCollectionNumDocsResponse(struct soap*, const char *, int, mindcall__setCollectionNumDocsResponse *const*, const char *);
SOAP_FMAC1 mindcall__setCollectionNumDocsResponse ** SOAP_FMAC2 soap_get_PointerTomindcall__setCollectionNumDocsResponse(struct soap*, mindcall__setCollectionNumDocsResponse **, const char*, const char*);
SOAP_FMAC1 mindcall__setCollectionNumDocsResponse ** SOAP_FMAC2 soap_in_PointerTomindcall__setCollectionNumDocsResponse(struct soap*, const char*, mindcall__setCollectionNumDocsResponse **, const char*);

#ifndef SOAP_PointerTomindcall__getSchemaResponse
#define SOAP_PointerTomindcall__getSchemaResponse (50)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTomindcall__getSchemaResponse(struct soap*, mindcall__getSchemaResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTomindcall__getSchemaResponse(struct soap*, mindcall__getSchemaResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTomindcall__getSchemaResponse(mindcall__getSchemaResponse **);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_PointerTomindcall__getSchemaResponse(struct soap*, mindcall__getSchemaResponse **, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_PointerTomindcall__getSchemaResponse(struct soap*, const char *, int, mindcall__getSchemaResponse *const*, const char *);
SOAP_FMAC1 mindcall__getSchemaResponse ** SOAP_FMAC2 soap_get_PointerTomindcall__getSchemaResponse(struct soap*, mindcall__getSchemaResponse **, const char*, const char*);
SOAP_FMAC1 mindcall__getSchemaResponse ** SOAP_FMAC2 soap_in_PointerTomindcall__getSchemaResponse(struct soap*, const char*, mindcall__getSchemaResponse **, const char*);

#ifndef SOAP_PointerTomindcall__extractQBSFeaturesResponse
#define SOAP_PointerTomindcall__extractQBSFeaturesResponse (51)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTomindcall__extractQBSFeaturesResponse(struct soap*, mindcall__extractQBSFeaturesResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTomindcall__extractQBSFeaturesResponse(struct soap*, mindcall__extractQBSFeaturesResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTomindcall__extractQBSFeaturesResponse(mindcall__extractQBSFeaturesResponse **);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_PointerTomindcall__extractQBSFeaturesResponse(struct soap*, mindcall__extractQBSFeaturesResponse **, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_PointerTomindcall__extractQBSFeaturesResponse(struct soap*, const char *, int, mindcall__extractQBSFeaturesResponse *const*, const char *);
SOAP_FMAC1 mindcall__extractQBSFeaturesResponse ** SOAP_FMAC2 soap_get_PointerTomindcall__extractQBSFeaturesResponse(struct soap*, mindcall__extractQBSFeaturesResponse **, const char*, const char*);
SOAP_FMAC1 mindcall__extractQBSFeaturesResponse ** SOAP_FMAC2 soap_in_PointerTomindcall__extractQBSFeaturesResponse(struct soap*, const char*, mindcall__extractQBSFeaturesResponse **, const char*);

#ifndef SOAP_PointerTomindtype__FeatureList
#define SOAP_PointerTomindtype__FeatureList (52)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTomindtype__FeatureList(struct soap*, mindtype__FeatureList *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTomindtype__FeatureList(struct soap*, mindtype__FeatureList *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTomindtype__FeatureList(mindtype__FeatureList **);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_PointerTomindtype__FeatureList(struct soap*, mindtype__FeatureList **, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_PointerTomindtype__FeatureList(struct soap*, const char *, int, mindtype__FeatureList *const*, const char *);
SOAP_FMAC1 mindtype__FeatureList ** SOAP_FMAC2 soap_get_PointerTomindtype__FeatureList(struct soap*, mindtype__FeatureList **, const char*, const char*);
SOAP_FMAC1 mindtype__FeatureList ** SOAP_FMAC2 soap_in_PointerTomindtype__FeatureList(struct soap*, const char*, mindtype__FeatureList **, const char*);

#ifndef SOAP_PointerTomindcall__queryResponse
#define SOAP_PointerTomindcall__queryResponse (53)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTomindcall__queryResponse(struct soap*, mindcall__queryResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTomindcall__queryResponse(struct soap*, mindcall__queryResponse *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTomindcall__queryResponse(mindcall__queryResponse **);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_PointerTomindcall__queryResponse(struct soap*, mindcall__queryResponse **, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_PointerTomindcall__queryResponse(struct soap*, const char *, int, mindcall__queryResponse *const*, const char *);
SOAP_FMAC1 mindcall__queryResponse ** SOAP_FMAC2 soap_get_PointerTomindcall__queryResponse(struct soap*, mindcall__queryResponse **, const char*, const char*);
SOAP_FMAC1 mindcall__queryResponse ** SOAP_FMAC2 soap_in_PointerTomindcall__queryResponse(struct soap*, const char*, mindcall__queryResponse **, const char*);

#ifndef SOAP_PointerTomindtype__PropResult
#define SOAP_PointerTomindtype__PropResult (54)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTomindtype__PropResult(struct soap*, mindtype__PropResult *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTomindtype__PropResult(struct soap*, mindtype__PropResult *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTomindtype__PropResult(mindtype__PropResult **);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_PointerTomindtype__PropResult(struct soap*, mindtype__PropResult **, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_PointerTomindtype__PropResult(struct soap*, const char *, int, mindtype__PropResult *const*, const char *);
SOAP_FMAC1 mindtype__PropResult ** SOAP_FMAC2 soap_get_PointerTomindtype__PropResult(struct soap*, mindtype__PropResult **, const char*, const char*);
SOAP_FMAC1 mindtype__PropResult ** SOAP_FMAC2 soap_in_PointerTomindtype__PropResult(struct soap*, const char*, mindtype__PropResult **, const char*);

#ifndef SOAP_PointerTomindtype__PropDocument
#define SOAP_PointerTomindtype__PropDocument (55)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTomindtype__PropDocument(struct soap*, mindtype__PropDocument *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTomindtype__PropDocument(struct soap*, mindtype__PropDocument *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTomindtype__PropDocument(mindtype__PropDocument **);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_PointerTomindtype__PropDocument(struct soap*, mindtype__PropDocument **, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_PointerTomindtype__PropDocument(struct soap*, const char *, int, mindtype__PropDocument *const*, const char *);
SOAP_FMAC1 mindtype__PropDocument ** SOAP_FMAC2 soap_get_PointerTomindtype__PropDocument(struct soap*, mindtype__PropDocument **, const char*, const char*);
SOAP_FMAC1 mindtype__PropDocument ** SOAP_FMAC2 soap_in_PointerTomindtype__PropDocument(struct soap*, const char*, mindtype__PropDocument **, const char*);

#ifndef SOAP_PointerTomindtype__PropDocumentAttribute
#define SOAP_PointerTomindtype__PropDocumentAttribute (56)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTomindtype__PropDocumentAttribute(struct soap*, mindtype__PropDocumentAttribute *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTomindtype__PropDocumentAttribute(struct soap*, mindtype__PropDocumentAttribute *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTomindtype__PropDocumentAttribute(mindtype__PropDocumentAttribute **);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_PointerTomindtype__PropDocumentAttribute(struct soap*, mindtype__PropDocumentAttribute **, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_PointerTomindtype__PropDocumentAttribute(struct soap*, const char *, int, mindtype__PropDocumentAttribute *const*, const char *);
SOAP_FMAC1 mindtype__PropDocumentAttribute ** SOAP_FMAC2 soap_get_PointerTomindtype__PropDocumentAttribute(struct soap*, mindtype__PropDocumentAttribute **, const char*, const char*);
SOAP_FMAC1 mindtype__PropDocumentAttribute ** SOAP_FMAC2 soap_in_PointerTomindtype__PropDocumentAttribute(struct soap*, const char*, mindtype__PropDocumentAttribute **, const char*);

#ifndef SOAP_PointerTomindtype__Query
#define SOAP_PointerTomindtype__Query (57)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTomindtype__Query(struct soap*, mindtype__Query *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTomindtype__Query(struct soap*, mindtype__Query *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTomindtype__Query(mindtype__Query **);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_PointerTomindtype__Query(struct soap*, mindtype__Query **, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_PointerTomindtype__Query(struct soap*, const char *, int, mindtype__Query *const*, const char *);
SOAP_FMAC1 mindtype__Query ** SOAP_FMAC2 soap_get_PointerTomindtype__Query(struct soap*, mindtype__Query **, const char*, const char*);
SOAP_FMAC1 mindtype__Query ** SOAP_FMAC2 soap_in_PointerTomindtype__Query(struct soap*, const char*, mindtype__Query **, const char*);

#ifndef SOAP_PointerTomindtype__Schema
#define SOAP_PointerTomindtype__Schema (58)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTomindtype__Schema(struct soap*, mindtype__Schema *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTomindtype__Schema(struct soap*, mindtype__Schema *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTomindtype__Schema(mindtype__Schema **);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_PointerTomindtype__Schema(struct soap*, mindtype__Schema **, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_PointerTomindtype__Schema(struct soap*, const char *, int, mindtype__Schema *const*, const char *);
SOAP_FMAC1 mindtype__Schema ** SOAP_FMAC2 soap_get_PointerTomindtype__Schema(struct soap*, mindtype__Schema **, const char*, const char*);
SOAP_FMAC1 mindtype__Schema ** SOAP_FMAC2 soap_in_PointerTomindtype__Schema(struct soap*, const char*, mindtype__Schema **, const char*);

#ifndef SOAP_PointerTomindtype__PropQueryCondition
#define SOAP_PointerTomindtype__PropQueryCondition (59)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTomindtype__PropQueryCondition(struct soap*, mindtype__PropQueryCondition *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTomindtype__PropQueryCondition(struct soap*, mindtype__PropQueryCondition *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTomindtype__PropQueryCondition(mindtype__PropQueryCondition **);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_PointerTomindtype__PropQueryCondition(struct soap*, mindtype__PropQueryCondition **, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_PointerTomindtype__PropQueryCondition(struct soap*, const char *, int, mindtype__PropQueryCondition *const*, const char *);
SOAP_FMAC1 mindtype__PropQueryCondition ** SOAP_FMAC2 soap_get_PointerTomindtype__PropQueryCondition(struct soap*, mindtype__PropQueryCondition **, const char*, const char*);
SOAP_FMAC1 mindtype__PropQueryCondition ** SOAP_FMAC2 soap_in_PointerTomindtype__PropQueryCondition(struct soap*, const char*, mindtype__PropQueryCondition **, const char*);

#ifndef SOAP_PointerToSchemaAttributeArray
#define SOAP_PointerToSchemaAttributeArray (60)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerToSchemaAttributeArray(struct soap*, SchemaAttributeArray *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerToSchemaAttributeArray(struct soap*, SchemaAttributeArray *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerToSchemaAttributeArray(SchemaAttributeArray **);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_PointerToSchemaAttributeArray(struct soap*, SchemaAttributeArray **, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_PointerToSchemaAttributeArray(struct soap*, const char *, int, SchemaAttributeArray *const*, const char *);
SOAP_FMAC1 SchemaAttributeArray ** SOAP_FMAC2 soap_get_PointerToSchemaAttributeArray(struct soap*, SchemaAttributeArray **, const char*, const char*);
SOAP_FMAC1 SchemaAttributeArray ** SOAP_FMAC2 soap_in_PointerToSchemaAttributeArray(struct soap*, const char*, SchemaAttributeArray **, const char*);

#ifndef SOAP_PointerToPointerTomindtype__SchemaAttribute
#define SOAP_PointerToPointerTomindtype__SchemaAttribute (61)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerToPointerTomindtype__SchemaAttribute(struct soap*, mindtype__SchemaAttribute **const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerToPointerTomindtype__SchemaAttribute(struct soap*, mindtype__SchemaAttribute **const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerToPointerTomindtype__SchemaAttribute(mindtype__SchemaAttribute ***);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_PointerToPointerTomindtype__SchemaAttribute(struct soap*, mindtype__SchemaAttribute ***, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_PointerToPointerTomindtype__SchemaAttribute(struct soap*, const char *, int, mindtype__SchemaAttribute **const*, const char *);
SOAP_FMAC1 mindtype__SchemaAttribute *** SOAP_FMAC2 soap_get_PointerToPointerTomindtype__SchemaAttribute(struct soap*, mindtype__SchemaAttribute ***, const char*, const char*);
SOAP_FMAC1 mindtype__SchemaAttribute *** SOAP_FMAC2 soap_in_PointerToPointerTomindtype__SchemaAttribute(struct soap*, const char*, mindtype__SchemaAttribute ***, const char*);

#ifndef SOAP_PointerTomindtype__SchemaAttribute
#define SOAP_PointerTomindtype__SchemaAttribute (62)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerTomindtype__SchemaAttribute(struct soap*, mindtype__SchemaAttribute *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerTomindtype__SchemaAttribute(struct soap*, mindtype__SchemaAttribute *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerTomindtype__SchemaAttribute(mindtype__SchemaAttribute **);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_PointerTomindtype__SchemaAttribute(struct soap*, mindtype__SchemaAttribute **, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_PointerTomindtype__SchemaAttribute(struct soap*, const char *, int, mindtype__SchemaAttribute *const*, const char *);
SOAP_FMAC1 mindtype__SchemaAttribute ** SOAP_FMAC2 soap_get_PointerTomindtype__SchemaAttribute(struct soap*, mindtype__SchemaAttribute **, const char*, const char*);
SOAP_FMAC1 mindtype__SchemaAttribute ** SOAP_FMAC2 soap_in_PointerTomindtype__SchemaAttribute(struct soap*, const char*, mindtype__SchemaAttribute **, const char*);

#ifndef SOAP_PointerToxsd__string
#define SOAP_PointerToxsd__string (63)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_PointerToxsd__string(struct soap*, char **const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_PointerToxsd__string(struct soap*, char **const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_PointerToxsd__string(char ***);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_PointerToxsd__string(struct soap*, char ***, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_PointerToxsd__string(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC1 char *** SOAP_FMAC2 soap_get_PointerToxsd__string(struct soap*, char ***, const char*, const char*);
SOAP_FMAC1 char *** SOAP_FMAC2 soap_in_PointerToxsd__string(struct soap*, const char*, char ***, const char*);

#ifndef SOAP_xsd__string
#define SOAP_xsd__string (64)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_xsd__string(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_xsd__string(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_xsd__string(char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_xsd__string(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_xsd__string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_xsd__string(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_xsd__string(struct soap*, const char*, char **, const char*);

#ifndef SOAP_string
#define SOAP_string (65)
#endif
SOAP_FMAC1 void SOAP_FMAC2 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_mark_string(struct soap*, char *const*);
SOAP_FMAC1 void SOAP_FMAC2 soap_default_string(char **);
SOAP_FMAC1 void SOAP_FMAC2 soap_put_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 void SOAP_FMAC2 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC1 char ** SOAP_FMAC2 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC1 char * * SOAP_FMAC2 soap_in_string(struct soap*, const char*, char **, const char*);
#endif

/* end of soapH.h */
