/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package lemurproject.lemur;

public class DocumentManager {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DocumentManager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DocumentManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      lemurJNI.delete_DocumentManager(swigCPtr);
    }
    swigCPtr = 0;
  }

  public String getDoc(String docID) {
    return lemurJNI.DocumentManager_getDoc(swigCPtr, docID);
  }

  public String docElement(String docid, String elt) {
    return lemurJNI.DocumentManager_docElement(swigCPtr, docid, elt);
  }

}
