/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package lemurproject.lemur;

public class IndriRetMethod extends RetrievalMethod {
  private long swigCPtr;

  protected IndriRetMethod(long cPtr, boolean cMemoryOwn) {
    super(lemurJNI.SWIGIndriRetMethodUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IndriRetMethod obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      lemurJNI.delete_IndriRetMethod(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

        /**
           Run an Indri structured query.
           @param searchQuery the query to run
           @return array of IndexedReal results
           @throws Exception if a lemur::api::Exception was thrown by the JNI library.
        */

public IndexedReal[] runQuery(String searchQuery) throws Exception {
  return RetMethodManager.runQuery(searchQuery, this);
}
 
}
