/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package lemurproject.lemur;

public class MatchInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MatchInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MatchInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      throw new UnsupportedOperationException("C++ destructor does not have public access");
    }
    swigCPtr = 0;
  }

  
/**
       Construct the match list for a given query/document pair.
@throws Exception if a lemur::api::Exception was thrown by the JNI library.
*/
public static TMatch[] getMatches(Index ind, Query qry, int docID) throws java.lang.Exception {
  return lemurJNI.MatchInfo_getMatches(Index.getCPtr(ind), ind, Query.getCPtr(qry), qry, docID);
}

}
