/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package lemurproject.lemur;

public class TermInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TermInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TermInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      lemurJNI.delete_TermInfo(swigCPtr);
    }
    swigCPtr = 0;
  }

  public TermInfo(int termID, int termCount) {
    this(lemurJNI.new_TermInfo(termID, termCount), true);
  }

  public int termID() {
    return lemurJNI.TermInfo_termID(swigCPtr);
  }

  public int count() {
    return lemurJNI.TermInfo_count(swigCPtr);
  }

  public int[] positions() {
  return lemurJNI.TermInfo_positions(swigCPtr);
}

  public int position() {
    return lemurJNI.TermInfo_position(swigCPtr);
  }

}
