/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Indri {

using System;
using System.Runtime.InteropServices;

public class ParsedDocument : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ParsedDocument(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ParsedDocument obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ParsedDocument() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      indriPINVOKE.delete_ParsedDocument(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public string text {
    set {
      indriPINVOKE.ParsedDocument_text_set(swigCPtr, value);
    } 
    get {
      string ret = indriPINVOKE.ParsedDocument_text_get(swigCPtr);
      return ret;
    } 
  }

  public uint textLength {
    set {
      indriPINVOKE.ParsedDocument_textLength_set(swigCPtr, value);
    } 
    get {
      uint ret = indriPINVOKE.ParsedDocument_textLength_get(swigCPtr);
      return ret;
    } 
  }

  public string content {
    set {
      indriPINVOKE.ParsedDocument_content_set(swigCPtr, value);
    } 
    get {
      string ret = indriPINVOKE.ParsedDocument_content_get(swigCPtr);
      return ret;
    } 
  }

  public uint contentLength {
    set {
      indriPINVOKE.ParsedDocument_contentLength_set(swigCPtr, value);
    } 
    get {
      uint ret = indriPINVOKE.ParsedDocument_contentLength_get(swigCPtr);
      return ret;
    } 
  }

  public string getContent() {
    string ret = indriPINVOKE.ParsedDocument_getContent(swigCPtr);
    return ret;
  }

  public TermExtentVector positions {
    set {
      indriPINVOKE.ParsedDocument_positions_set(swigCPtr, TermExtentVector.getCPtr(value));
    } 
    get {
      IntPtr cPtr = indriPINVOKE.ParsedDocument_positions_get(swigCPtr);
      TermExtentVector ret = (cPtr == IntPtr.Zero) ? null : new TermExtentVector(cPtr, false);
      return ret;
    } 
  }

  public MetadataPairVector metadata {
    set {
      indriPINVOKE.ParsedDocument_metadata_set(swigCPtr, MetadataPairVector.getCPtr(value));
    } 
    get {
      IntPtr cPtr = indriPINVOKE.ParsedDocument_metadata_get(swigCPtr);
      MetadataPairVector ret = (cPtr == IntPtr.Zero) ? null : new MetadataPairVector(cPtr, false);
      return ret;
    } 
  }

  public ParsedDocument() : this(indriPINVOKE.new_ParsedDocument(), true) {
  }

}

}
