/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Indri {

using System;
using System.Runtime.InteropServices;

public class Specification : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Specification(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Specification obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Specification() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      indriPINVOKE.delete_Specification(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public string name {
    set {
      indriPINVOKE.Specification_name_set(swigCPtr, value);
      if (indriPINVOKE.SWIGPendingException.Pending) throw indriPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = indriPINVOKE.Specification_name_get(swigCPtr);
      if (indriPINVOKE.SWIGPendingException.Pending) throw indriPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string parser {
    set {
      indriPINVOKE.Specification_parser_set(swigCPtr, value);
      if (indriPINVOKE.SWIGPendingException.Pending) throw indriPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = indriPINVOKE.Specification_parser_get(swigCPtr);
      if (indriPINVOKE.SWIGPendingException.Pending) throw indriPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string tokenizer {
    set {
      indriPINVOKE.Specification_tokenizer_set(swigCPtr, value);
      if (indriPINVOKE.SWIGPendingException.Pending) throw indriPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = indriPINVOKE.Specification_tokenizer_get(swigCPtr);
      if (indriPINVOKE.SWIGPendingException.Pending) throw indriPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string iterator {
    set {
      indriPINVOKE.Specification_iterator_set(swigCPtr, value);
      if (indriPINVOKE.SWIGPendingException.Pending) throw indriPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = indriPINVOKE.Specification_iterator_get(swigCPtr);
      if (indriPINVOKE.SWIGPendingException.Pending) throw indriPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string startDocTag {
    set {
      indriPINVOKE.Specification_startDocTag_set(swigCPtr, value);
      if (indriPINVOKE.SWIGPendingException.Pending) throw indriPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = indriPINVOKE.Specification_startDocTag_get(swigCPtr);
      if (indriPINVOKE.SWIGPendingException.Pending) throw indriPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string endDocTag {
    set {
      indriPINVOKE.Specification_endDocTag_set(swigCPtr, value);
      if (indriPINVOKE.SWIGPendingException.Pending) throw indriPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = indriPINVOKE.Specification_endDocTag_get(swigCPtr);
      if (indriPINVOKE.SWIGPendingException.Pending) throw indriPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string endMetadataTag {
    set {
      indriPINVOKE.Specification_endMetadataTag_set(swigCPtr, value);
      if (indriPINVOKE.SWIGPendingException.Pending) throw indriPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = indriPINVOKE.Specification_endMetadataTag_get(swigCPtr);
      if (indriPINVOKE.SWIGPendingException.Pending) throw indriPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public StringVector include {
    set {
      indriPINVOKE.Specification_include_set(swigCPtr, StringVector.getCPtr(value));
    } 
    get {
      IntPtr cPtr = indriPINVOKE.Specification_include_get(swigCPtr);
      StringVector ret = (cPtr == IntPtr.Zero) ? null : new StringVector(cPtr, false);
      return ret;
    } 
  }

  public StringVector exclude {
    set {
      indriPINVOKE.Specification_exclude_set(swigCPtr, StringVector.getCPtr(value));
    } 
    get {
      IntPtr cPtr = indriPINVOKE.Specification_exclude_get(swigCPtr);
      StringVector ret = (cPtr == IntPtr.Zero) ? null : new StringVector(cPtr, false);
      return ret;
    } 
  }

  public StringVector index {
    set {
      indriPINVOKE.Specification_index_set(swigCPtr, StringVector.getCPtr(value));
    } 
    get {
      IntPtr cPtr = indriPINVOKE.Specification_index_get(swigCPtr);
      StringVector ret = (cPtr == IntPtr.Zero) ? null : new StringVector(cPtr, false);
      return ret;
    } 
  }

  public StringVector metadata {
    set {
      indriPINVOKE.Specification_metadata_set(swigCPtr, StringVector.getCPtr(value));
    } 
    get {
      IntPtr cPtr = indriPINVOKE.Specification_metadata_get(swigCPtr);
      StringVector ret = (cPtr == IntPtr.Zero) ? null : new StringVector(cPtr, false);
      return ret;
    } 
  }

  public ConfMap conflations {
    set {
      indriPINVOKE.Specification_conflations_set(swigCPtr, ConfMap.getCPtr(value));
    } 
    get {
      IntPtr cPtr = indriPINVOKE.Specification_conflations_get(swigCPtr);
      ConfMap ret = (cPtr == IntPtr.Zero) ? null : new ConfMap(cPtr, false);
      return ret;
    } 
  }

  public Specification() : this(indriPINVOKE.new_Specification(), true) {
  }

}

}
