/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Lemur {

using System;
using System.Runtime.InteropServices;

public class TMatchVector : IDisposable, System.Collections.IEnumerable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TMatchVector(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TMatchVector obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TMatchVector() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        lemur_csharpPINVOKE.delete_TMatchVector(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
    }
  }

  public TMatchVector(System.Collections.ICollection c) : this() {
    if (c == null)
      throw new ArgumentNullException("c");
    foreach (TMatch element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public TMatch this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(System.Array array) {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(System.Array array, int arrayIndex) {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, System.Array array, int arrayIndex, int count) {
    if (array == null)
      throw new ArgumentNullException("array");
    if (index < 0)
      throw new ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new ArgumentException("Multi dimensional array.");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  // Type-safe version of IEnumerable.GetEnumerator
  System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() {
    return new TMatchVectorEnumerator(this);
  }

  public TMatchVectorEnumerator GetEnumerator() {
    return new TMatchVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class TMatchVectorEnumerator : System.Collections.IEnumerator {
    private TMatchVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public TMatchVectorEnumerator(TMatchVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public TMatch Current {
      get {
        if (currentIndex == -1)
          throw new InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new InvalidOperationException("Collection modified.");
        return (TMatch)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new InvalidOperationException("Collection modified.");
      }
    }
  }

  public void Clear() {
    lemur_csharpPINVOKE.TMatchVector_Clear(swigCPtr);
  }

  public void Add(TMatch x) {
    lemur_csharpPINVOKE.TMatchVector_Add(swigCPtr, TMatch.getCPtr(x));
    if (lemur_csharpPINVOKE.SWIGPendingException.Pending) throw lemur_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = lemur_csharpPINVOKE.TMatchVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = lemur_csharpPINVOKE.TMatchVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    lemur_csharpPINVOKE.TMatchVector_reserve(swigCPtr, n);
  }

  public TMatchVector() : this(lemur_csharpPINVOKE.new_TMatchVector__SWIG_0(), true) {
  }

  public TMatchVector(int capacity) : this(lemur_csharpPINVOKE.new_TMatchVector__SWIG_1(capacity), true) {
    if (lemur_csharpPINVOKE.SWIGPendingException.Pending) throw lemur_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  private TMatch getitemcopy(int index) {
    TMatch ret = new TMatch(lemur_csharpPINVOKE.TMatchVector_getitemcopy(swigCPtr, index), true);
    if (lemur_csharpPINVOKE.SWIGPendingException.Pending) throw lemur_csharpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private TMatch getitem(int index) {
    TMatch ret = new TMatch(lemur_csharpPINVOKE.TMatchVector_getitem(swigCPtr, index), false);
    if (lemur_csharpPINVOKE.SWIGPendingException.Pending) throw lemur_csharpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, TMatch val) {
    lemur_csharpPINVOKE.TMatchVector_setitem(swigCPtr, index, TMatch.getCPtr(val));
    if (lemur_csharpPINVOKE.SWIGPendingException.Pending) throw lemur_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(TMatchVector values) {
    lemur_csharpPINVOKE.TMatchVector_AddRange(swigCPtr, TMatchVector.getCPtr(values));
    if (lemur_csharpPINVOKE.SWIGPendingException.Pending) throw lemur_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public TMatchVector GetRange(int index, int count) {
    IntPtr cPtr = lemur_csharpPINVOKE.TMatchVector_GetRange(swigCPtr, index, count);
    TMatchVector ret = (cPtr == IntPtr.Zero) ? null : new TMatchVector(cPtr, true);
    if (lemur_csharpPINVOKE.SWIGPendingException.Pending) throw lemur_csharpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, TMatch x) {
    lemur_csharpPINVOKE.TMatchVector_Insert(swigCPtr, index, TMatch.getCPtr(x));
    if (lemur_csharpPINVOKE.SWIGPendingException.Pending) throw lemur_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, TMatchVector values) {
    lemur_csharpPINVOKE.TMatchVector_InsertRange(swigCPtr, index, TMatchVector.getCPtr(values));
    if (lemur_csharpPINVOKE.SWIGPendingException.Pending) throw lemur_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    lemur_csharpPINVOKE.TMatchVector_RemoveAt(swigCPtr, index);
    if (lemur_csharpPINVOKE.SWIGPendingException.Pending) throw lemur_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    lemur_csharpPINVOKE.TMatchVector_RemoveRange(swigCPtr, index, count);
    if (lemur_csharpPINVOKE.SWIGPendingException.Pending) throw lemur_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public static TMatchVector Repeat(TMatch value, int count) {
    IntPtr cPtr = lemur_csharpPINVOKE.TMatchVector_Repeat(TMatch.getCPtr(value), count);
    TMatchVector ret = (cPtr == IntPtr.Zero) ? null : new TMatchVector(cPtr, true);
    if (lemur_csharpPINVOKE.SWIGPendingException.Pending) throw lemur_csharpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    lemur_csharpPINVOKE.TMatchVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    lemur_csharpPINVOKE.TMatchVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (lemur_csharpPINVOKE.SWIGPendingException.Pending) throw lemur_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, TMatchVector values) {
    lemur_csharpPINVOKE.TMatchVector_SetRange(swigCPtr, index, TMatchVector.getCPtr(values));
    if (lemur_csharpPINVOKE.SWIGPendingException.Pending) throw lemur_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
