
# define dependent modules
# Assuming dependence on all library modules. In the future
# each application should have its own dependent list (to be fixed later)

DEPENDMODS = distrib retrieval langmod index utility 


include ../../MakeApp
