

#define this module
MODULE	= index

#define the modules it depends on
#important: the order should reflect the desired order for linking
DEPENDMODS = utility

# IN GENERAL,  DO NOT CHANGE ANY LINES BELOW THIS POINT

#include the common definitions/rules for a module directory
include ../../MakeMod
