

#define this module
MODULE	= summarization

#define the modules it depends on
#important: the order should reflect the desired order for linking
DEPENDMODS = langmod index utility

# IN GENERAL,  DO NOT CHANGE ANY LINES BELOW THIS POINT

include ../../MakeMod
